language: haskell
script: "make ci"
notifications:
  email:
    recipients:
      - cloud.haskell@gmail.com
  irc:
    channels:
      - "irc.freenode.org#haskell-distributed"
    use_notice: true
branches:
  only:
    - master
    - development
