language: haskell
script: "make ci"
install: "make deps"
notifications:
  email:
    recipients:
      - cloud.haskell@gmail.com
  irc:
    channels:
      - "irc.freenode.org#haskell-distributed"
    use_notice: true
